# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               MintSnail
tagline:             The Mint Snail
url:                 http://mintsnail.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Soojin Kim
  url:               https://facebook.com/reedpipe
  email:             soojin66@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
